77 multiple filters feature
kuoss/lethe pull request #79
Opened 2023-05-22 08:36 UTC by jmnote

#### What this PR does / why we need it (변경 내용 / 필요성): 

- 멀티 필터 연산자 기능

#### Which issue(s) this PR fixes (관련 이슈):

- #77 

#### Special notes for your reviewer (리뷰어에게 하고 싶은 말):

리뷰 감사합니다. 변경 내용이 많아 죄송
기능을 구현하고 보니까, 
promql에 맞출 수 있는 부분이 계속 발견되서 수정, 수정, 수정...

대략적인 규격은 맞췄지만 Querier는 껍데기만 있고요.
패키지 통폐합 등 여전히 개선포인트는 많이 남아 있습니다.

#### Additional documentation, usage docs, etc. (기타 관련 문서, 사용법 등):

변경된 구조에 대해서는 아래 다이어그램을 참고하시고요.

https://github.com/kuoss/lethe/blob/main/docs/diagram.md

2023-05-22 10:19 UTC, jmnote commented
커버리지 때문에 삽질 중...
github actions나 goveralls 문제가 아니라 go tool cover로 해도 동일한 문제가 있네요.

```
~/gopath/src/lethe$ go test -race -covermode atomic -coverprofile=coverage.out ./...
?       github.com/kuoss/lethe  [no test files]
ok      github.com/kuoss/lethe/clock    0.048s  coverage: 100.0% of statements
ok      github.com/kuoss/lethe/config   0.061s  coverage: 84.8% of statements
?       github.com/kuoss/lethe/letheql/model    [no test files]
ok      github.com/kuoss/lethe/handler  0.195s  coverage: 87.9% of statements
ok      github.com/kuoss/lethe/letheql  0.126s  coverage: 37.3% of statements
?       github.com/kuoss/lethe/storage/driver/filesystem/disk   [no test files]
?       github.com/kuoss/lethe/storage/logservice/logmodel      [no test files]
?       github.com/kuoss/lethe/storage/logservice/match [no test files]
?       github.com/kuoss/lethe/util/testutil    [no test files]
ok      github.com/kuoss/lethe/letheql/parser   115.751s        coverage: 83.6% of statements
ok      github.com/kuoss/lethe/rotator  0.114s  coverage: 46.2% of statements
ok      github.com/kuoss/lethe/storage/driver   0.088s  coverage: 94.4% of statements
ok      github.com/kuoss/lethe/storage/driver/factory   0.054s  coverage: 100.0% of statements
ok      github.com/kuoss/lethe/storage/driver/factory/fake      0.042s  coverage: 100.0% of statements
ok      github.com/kuoss/lethe/storage/driver/filesystem        0.125s  coverage: 78.5% of statements
ok      github.com/kuoss/lethe/storage/fileservice      0.163s  coverage: 68.0% of statements
ok      github.com/kuoss/lethe/storage/logservice       0.067s  coverage: 1.1% of statements
ok      github.com/kuoss/lethe/storage/querier  0.048s  coverage: 0.0% of statements [no tests to run]
ok      github.com/kuoss/lethe/storage/queryservice     0.065s  coverage: 87.5% of statements
ok      github.com/kuoss/lethe/util     0.052s  coverage: 81.6% of statements
```
```
~/gopath/src/lethe$ go tool cover -func coverage.out
cover: inconsistent NumStmt: changed from 1 to 2
```

2023-05-22 11:13 UTC, jmnote commented
커버리지 69.747%

2023-05-22 11:15 UTC, jmnote commented on .github/workflows/pull-request.yml
> +    - run: cat coverprofile | grep -v yaccpar > coverage.out
커버리지 계산에 문제가 있어서 당분간 yaccpar (goyacc parser)는 제외합니다.

2023-05-22 12:13 UTC, jmnote commented on codecov.yml
> +#comment: false
codecov comment를 다시 살려봅니다...

2023-05-22 12:15 UTC, jmnote commented on clock/clock.go
> +}
TEST_MODE라는 환경 변수 대신, playgroundMode 라는 좀더 구체적인 설정으로 바꿔봤습니다. Go Playground의 시계와 동일하게 맞춘다는 의미입니다.

2023-05-22 12:19 UTC, jmnote commented on config/config.go
> +}
기존에는 vip(viper) 멤버변수를 가지고 있고 Viper() 메소드를 통해 아무 설정 변수나 다 접근할 수 있었는데, vip과 Viper()를 제거하고 구체적인 멤버변수와 메소드를 명시하여 추가하였습니다.

2023-05-23 03:09 UTC, jmnote commented on handler/handler.go
> +package handler
이름이나 포함 관계가 고민이 되긴 했는데, router 없이 handler를 테스트하려면 각 테스트 코드에서 route를 설정해야 하는 번거로움이 있어서, 하나의 패키지로 통합하고 handler 패키지 내부에서 router를 설정하고 route별로 테스트함으로서 각 handler 함수들을 테스트하는 구조로 변경하였습니다.

2023-05-25 11:47 UTC, jmnote commented
https://github.com/kuoss/lethe/pull/79/commits/13486e7bd5d063ba51d1dfb55e6cbf5f5198900b
마지막 커밋은 https://github.com/kuoss/lethe/issues/80 관련입니다.

2023-05-26 00:29 UTC, dozer-jang requested changes
오프라인 코드 리뷰를 통해 전체적인 PR을 설명 듣고 작성하는 리뷰입니다.

1. PR의 중심이되는 `letheql/engine.go, evaluator.go`가 매우 인상적이었습니다. 특히 불필요한 메모리 로딩을 피하기 위해 `filterOperator` 처리를 마지막으로 미루기 위해 `LogSelector`타입의 도입이 좋습니다. `promql`의 장점과 과도한 엔지니어링을 걷어낸 부분도 보기 좋은 코드 같습니다.

2. `letheql`만큼 인상적인 `logservice/match` 패키지입니다. `MatchFunc` 타입의 사용은 다른 패키지에서도 참고할만한 좋은 레퍼런스이고 멋진 코드 같습니다. 다른 곳에서 사용하는 모습은 많이 보아도 막상 직접 사용하는 경우는 없었는데 좋은 레퍼런스입니다.

3. 테스트 환경이 쾌적해진 것이 체감이 많이 됩니다. race detector를 켜놓고 전체 패키지를 테스트해도 걱정 없이 테스트 완료됩니다. 테스트 코드 양과 커버리지 모두 훌륭합니다.

4. 개별 코드에 대한 코멘트를 참고만 해주세요. 대부분은 컨벤션에 해당하는 내용입니다. 패키지 네이밍, TODO를 위한 아카이빙 등


당부드리고 싶은 점
1. PR을 조금만 작게 작성해주세요. 물론 letheql의 구조가 변경되면서 handler -> service -> letheql -> storage 전체 파이프라인에 대한 조정이 필요했기에 어쩔 수 없다는 것은 알지만, 너무 PR이 크다보니 리뷰하는데 조금 겁을 먹고 시작했습니다. 저도 잘 못지키는 부분이지만 지금부터 지켜보겠습니다.

2. git이 인식할 수 있도록 디렉토리 변경, 파일 삭제, 파일 이동을 해주세요.

3. 패키지명을 바꾸는 것은 괜찮지만 레이어(service, handler, storage)등 전체 레이어 구조에 대한 변경은 같이 논의 후 진행했으면 좋겠습니다. 이번 PR에서도 storage 레이어 쪽으로 대부분의 서비스들이 옮겨갔고, 저도 그 의도에 동의하지만 해당 내용을 미리 알았다면 더 좋았을 것 같습니다.


PS 일단 Request Change로 리뷰하고 코멘트들에 의견 주시면 approval하겠습니다~

2023-05-26 00:29 UTC, dozer-jang commented on storage/fileservice/clean.go
> +	files, err := filepath.Glob(fmt.Sprintf("%s/%s.*", s.config.LogDataPath(), prefix))
기존의 `storageDriver`를 이용해서 `FileInfo`를 통해서 처리해야하는 부분일 것 같습니다

2023-05-26 00:29 UTC, dozer-jang commented on storage/fileservice/list.go
> +		files, err := os.ReadDir(logDir.Fullpath)
기존의 `storageDriver`를 이용해서 `FileInfo`를 통해서 처리해야하는 부분일 것 같습니다

2023-05-26 00:29 UTC, dozer-jang commented on storage/logservice/logservice.go
> +	mfs, err := match.GetMatchFuncSet(sel)
멋진 부분 입니다.

2023-05-26 00:50 UTC, jmnote commented on storage/fileservice/list.go
> +		files, err := os.ReadDir(logDir.Fullpath)
네, 시간 되면 package/method 목록을 작성하고 어떻게 조정할지 논의하면 좋겠네요. ㅎㅎ

2023-05-26 01:10 UTC, jmnote commented on config/config.go
> +}
네 개선의 여지가 있네요 ㅎㅎ

2023-05-26 01:13 UTC, jmnote commented
의견 주신 내용들 잘 보았습니다. 추후 개선할 포인트들을 함께 확인하는 의미가 있었습니다. 리뷰 감사합니다~!

2023-05-26 01:24 UTC, dozer-jang commented
+) `logFormat=json`을 명시하지 않아도 json형태 응답이 기본값으로 변경

2023-05-26 01:25 UTC, dozer-jang approved these changes

2023-05-26 01:25 UTC, dozer-jang commented
Approval합니다 감사합니다~

2023-05-26 01:30 UTC, jmnote commented
리뷰 감사합니다. merge 합니다~!

2023-05-26 01:30 UTC, merged